name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Exécution quotidienne à minuit
  workflow_dispatch:     # Permet de lancer manuellement

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1: Génère l'animation snake
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        with:
          github_user_name: modervnt  # Remplacez par votre username
          svg_out_path: dist/github-contribution-snake.svg
          gif_out_path: dist/github-contribution-snake.gif
          # Options supplémentaires:
          # colors: "#1f9d55,#1a7b46"  # Couleurs personnalisées
          # transparent: 1            # Fond transparent

      # Étape 2: Téléverse l'animation
      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/
          
      # Étape 3: Déploie sur une branche (optionnel)
      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: snake-output  # Crée cette branche au préalable
